biz_mvp_profile:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: analytics
      password: analytics
      port: 5432
      dbname: bizmvp
      schema: raw
      threads: 4
      keepalives_idle: 0