version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: customers
      - name: products
      - name: orders

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique

  - name: stg_products
    columns:
      - name: product_id
        tests:
          - not_null
          - unique

  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
      - name: customer_id
        tests:
          - not_null
      - name: product_id
        tests:
          - not_null
